version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SalesforceStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-azokl7f1nvxf"
s3_prefix = "SalesforceStack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
